Some of the json files have floats not ints and structse need ints
To address this error. Cause the images contain floats.
Traceback (most recent call last):
  File "..\scripts\convert-animation.py", line 48, in <module>
    f.write(struct.pack('B', 255*column[color]))
struct.error: required argument is not an integer